---
title: Red Butte Garden
timezone: America/Denver
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: :title/
email: contact@redbuttegarden.org
description: The official website of Red Butte Garden
baseurl: ''
url: http://redbuttegarden.org
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- ".travis.yml"
permalink: pretty
prose:
  ignore:
    - _layouts
    - _site
    - templates
    - index.html
    - CSS
    - js
    - images/core

  events:
    _posts:
    - name: layout
      field:
        element: hidden
        value: "events"

  whats-blooming:
    _posts:
    - name: layout
      field:
        element: hidden
        value: "post"

url: "http://example.com" # the base hostname & protocol for your site
plugins_dir:
  - jekyll-sitemap
